# Generated by Django 6.1 on 2026-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '* '), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * ')], default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
